### ISSUE TITLE
Error importing pipeline "smart.py"

### ISSUE THREAD

**Issue by edv-sml** [MartianInGreen/OpenWebUI-Tools#1]
Hi, i wanted to import the smart.py into my pipeline docker container via openwebui pipeline import function.
Don't know if this is the way, maybe you can make a step by step idiot proof instruction :/

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
WARNING:root:No Pipeline class found in smart
https://raw.githubusercontent.com/MartianInGreen/OpenWebUI-Tools/main/pipes/smart.py
Installing requirement: langchain-openai==0.1.24
Installing requirement: langgraph
Loaded module: smart
Error loading module: smart
No Pipeline class found

**Comment by MartianInGreen** [comment]
Yeah, it's a function for the OpenWeb UI. So just go to Workspaces -> Functions -> Add New Function (the little + Icon) and then paste the raw code in there.

**Comment by edv-sml** [comment]
Oh, many thanks, i did it fia admin-settings -> pipelines.
looked at my pipeline docker container and there ifound this error.


and additionally in workspaces -> functions i forgot to enable it ^^ - just enabled and it's working instantly

**Comment by MartianInGreen** [comment]
No worries, don't forget to set you API Key! By default it uses OpenRouter but if you want to use another OpenAI compatible api you can change the Base URL, just don't forget to adjust the model names if you do that!

**Comment by edv-sml** [comment]
You are a genius! Works like a charme
